# Generated by Django 2.1.15 on 2021-01-15 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_course_student_balance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course_student',
            unique_together={('course', 'student')},
        ),
    ]
