# Generated by Django 2.1.15 on 2021-01-18 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210117_1847'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('name', 'phone', 'email')},
        ),
    ]
