# Generated by Django 2.1.15 on 2021-01-18 00:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210117_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_student',
            name='attend_times',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='course_student',
            name='paid_credit',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='course_student',
            name='score',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'period', 'place', 'price', 'start', 'end')},
        ),
    ]
