# Generated by Django 2.1.15 on 2021-01-18 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210117_1937'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'period', 'place')},
        ),
    ]
